# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-alpine

WORKDIR /app

# Upgrade pip
RUN pip install --upgrade pip

# Copy project files
COPY . .

# Install project dependencies, ignoring the Python version requirement
RUN pip install --no-cache-dir . --ignore-requires-python

CMD ["python", "src/mcp_server_calculator/calculator.py"]
