[project]
name = "mcp-server-calculator"
version = "0.0.1"
requires-python = ">=3.13"
dependencies = [
  "hatchling",
  "mcp",
  "mcp[cli]"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/mcp_server_calculator"]
